# Generated by Django 4.1.5 on 2024-01-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malayalam', models.IntegerField(max_length=3)),
                ('english', models.IntegerField(max_length=3)),
                ('science', models.IntegerField(max_length=3)),
            ],
        ),
    ]
